### ISSUE TITLE
Getting stream delegate callbacks not working

### ISSUE THREAD

**Issue by solas** [paulw11/L2CapDemo#1]
Hi Paul, you helped Michel with this a few months back, and I have a similar issue (buried in the final comments): I cannot get Stream Delegate callbacks (L2CAP callbacks like bytesAvailable) to work in my code (modeled after yours) ... do you recall the key items to check to make this work?
thanks in advance

**Comment by paulw11** [comment]
I can't recall anything in particular; If your delegate methods aren't being called then I suggest you check to ensure that all relevant objects are being held in `strong` properties - i.e. the `channel` object and your `delegate` object.
