### ISSUE TITLE
Possible to create mac cli tool to type text to bluetooth connected ios device

### ISSUE THREAD

**Issue by krishtoautomate** [paulw11/L2CapDemo#3]
Possible to create mac cli tool to type text to bluetooth connected ios device?

**Comment by paulw11** [comment]
Yes, it would be possible for you to do that.  The L2Cap framework works on macOS.  You would simply need to create a command line project in Xcode and incorporate the L2Cap framework with whatever logic you wanted to make a Bluetooth connection, collect the input and send it.  

Of course the Bluetooth device you are connecting to needs to support L2Cap as well
